### ISSUE TITLE
What is the real repository?

### ISSUE THREAD

**Issue by pauldendulk** [xamarin-libraries/sqlite.net-pcl-extensions#1]
There is also a repository on bitbucket: https://bitbucket.org/twincoders/sqlite-net-extensions. 

What is the real one? Where should I submit issues?

**Comment by ts-dk** [comment]
Hi Paul,

the one at bitbucket is the main repositoy, please submit issues there!

Merry Christmas!

Tobias Schulz

Von Outlook Mobile<https://aka.ms/blhgte> gesendet



On Sun, Dec 27, 2015 at 3:28 AM -0800, "Paul den Dulk" <notifications@github.com<mailto:notifications@github.com>> wrote:


There is also a repository on bitbucket: https://bitbucket.org/twincoders/sqlite-net-extensions.

What is the real one? Where should I submit issues?

-

**Comment by pauldendulk** [comment]
Thanks
